# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(to='app1.Group'),
        ),
    ]
