# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171107_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
    ]
